/**
 * Merge Plan — the pure decision behind "Merge finished parallel Runs" (issue
 * 08, ADR-0002).
 *
 * When Mission Control ran issues in parallel it gave each Run its own git
 * worktree on an `afk/NN-slug` branch (issue 07). Once those parallel Runs
 * finish, their work still lives on the branches — this module decides *when* a
 * human-triggered **Merge** action should appear on the Map, and *which* slugs
 * it would integrate. It never merges anything and never runs automatically:
 * the merge is always human-triggered (ADR-0002). The real git work is done by
 * `afk-merge.sh` via the main-process merge adapter (`run-merge.ts`).
 *
 * PURE (no git, no fs, no Electron) so the "is a Merge offered yet?" rule is
 * unit-testable in isolation (see PRD "Testing Decisions").
 *
 * Only **isolated** Runs (those that worked in a worktree on an `afk/` branch)
 * are merge candidates — a Run that stayed on `main` (solo, or the first Run of
 * a drain that started before parallel kicked in) already has its work on
 * `main` and needs no merge. Of those, only **finished** Runs are mergeable; a
 * blocked/stopped Run's branch holds incomplete work and is left alone.
 */
import type { RunStatus } from './run-state';

/** One Run considered for merging. */
export interface MergeRun {
  issueId: number;
  /** The `NN-slug` stem, matching the `afk/NN-slug` branch and worktree key. */
  slug: string;
  status: RunStatus;
  /** True when this Run worked in its own worktree on an `afk/` branch. */
  isolated: boolean;
}

/** A branch the Merge action would integrate. */
export interface MergeCandidate {
  issueId: number;
  slug: string;
}

export interface MergePlan {
  /**
   * Whether to surface the Merge action now: at least one finished isolated Run
   * exists AND no isolated Run is still running (the parallel batch is done).
   */
  ready: boolean;
  /** The finished isolated Runs whose `afk/` branches would be merged, by id. */
  mergeable: MergeCandidate[];
  /** Isolated Runs still running — why the Merge isn't offered yet (by id). */
  pendingRunning: number[];
}

/**
 * Decide whether a Merge action should appear and which branches it targets.
 * Deterministic and idempotent — safe to recompute on every state change.
 *
 * The Merge appears "once parallel Runs have finished, and not before": while
 * any isolated Run is still `running`, the batch isn't done, so `ready` is
 * false even if some siblings already finished.
 */
export function mergeReadiness(runs: MergeRun[]): MergePlan {
  const isolated = runs.filter((r) => r.isolated);

  const mergeable: MergeCandidate[] = isolated
    .filter((r) => r.status === 'finished')
    .sort((a, b) => a.issueId - b.issueId)
    .map((r) => ({ issueId: r.issueId, slug: r.slug }));

  const pendingRunning = isolated
    .filter((r) => r.status === 'running')
    .map((r) => r.issueId)
    .sort((a, b) => a - b);

  const ready = mergeable.length >= 1 && pendingRunning.length === 0;

  return { ready, mergeable, pendingRunning };
}

/**
 * The `<project>/issues/afk-merge.conf` body Mission Control writes so
 * `afk-merge.sh` targets a single-repo project: one repo, whose path is `.`
 * (resolved by the script against the project root). No CHOKEPOINTS and no
 * `test_<label>` are defined on purpose — every conflict then stops for the
 * human rather than being auto-resolved (issue 08 acceptance), and the merge
 * adapter runs the script with `--no-test` regardless.
 */
export function afkMergeConfContent(label = 'app'): string {
  return [
    '# Generated by Mission Control (issue 08) so afk-merge.sh can integrate',
    '# this single-repo project. "label|path"; "." resolves to the project root.',
    `REPOS=( "${label}|." )`,
    '',
  ].join('\n');
}
